### ISSUE TITLE
Support ETA, VoLTE functionality

### ISSUE THREAD

**Issue by UltraBlackLinux** [mlm-games/kernel_samsung_exynos_9611#3]
Hey there,
Just found this project and I'm considering to get an XCover, but I'm wondering for how long you're planning to support this project. I'm not in any way involved in anything android other than using it so I'm wondering if I'd be able to depend on this for prolonged daily use.

I also read online that Samsung's proprietary VoLTE implementation hasn't been reverse-engineered yet, so I'd assume that it  doesn't work on this build? 2G has already been shut off and I can't guarantee that 3G will stay around over here for as many years as I wanna use this phone for.

I'd be hoping for support similar to what LineageOS is known for, because re-installing the system would be a huge hassle. I know this is a lot to ask for but there just aren't a ton, if any, well supported custom ROMs for this phone...

Thanks!

**Comment by mlm-games** [comment]
VoLTE only makes it so your calls go through LTE instead of older voice networks (data won't work during calls), Your 4G or LTE will still work. As for the support, I don't have that much time nowadays but will try to respond if there is a serious problem (like it restarting every few secs... Etc)
